### ISSUE TITLE
Is this living on in any way?

### ISSUE THREAD

**Issue by vongohren** [mikeseese/velma#46]
Just wondering if there is any structure around this to make it live on further?

**Comment by mikeseese** [comment]
Thanks @vongohren for following up! This is not dead! I'm now a Truffle engineer, and we've been working on how to leverage Velma tech to enhance the Truffle debugger. This repo and the Velma brand may not live on, but we're working on keeping the tech in one, strong debugger. I'd look out for some official announcements by Truffle and myself/Velma sometime after TruffleCon once we have a game plan to make a professional-level debugger.

I truly apologize for the delay. Velma plans kind of drastically changed (for the best, we're super excited to move forward with these plans, they're just delayed) after my employment at Truffle settled in.

This **will** happen, and it's going to be _awesome_!!

**Comment by vongohren** [comment]
@seesemichaelj haha sounds great, then I will leave this for now, and follow the news

**Comment by crisgarner** [comment]
Great news! Looking forward the truffle announcements!

**Comment by vongohren** [comment]
Closing for completion
